version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-cadastro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cadastro
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3306:3306"

  web:
    build:
      context: .
      dockerfile: imp.dockerfile
    container_name: php-cadastro
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
